on: pull_request
name: CI
jobs:
  test:
    name: Unit Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=macOS,arch=x86_64']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild -project PomodoroCookie.xcodeproj -scheme PomodoroCookie -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES build test
          bash <(curl -s https://codecov.io/bash) -t b5d8eba3-62ac-4d0a-bec4-59dde08cbd02
        env: 
         destination: ${{ matrix.destination }}
