on: 
  push:
    branches:
      - 'master'
  pull_request:
    branches: 
      - 'master'

name: CI
jobs:
  test:
    name: Unit Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=macOS,arch=x86_64']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and test
        run: |
          xcodebuild -project Momentime.xcodeproj -enableCodeCoverage YES -scheme Momentime -destination "${destination}" ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO build test
          bash <(curl -s https://codecov.io/bash) -t b5d8eba3-62ac-4d0a-bec4-59dde08cbd02
        env: 
         destination: ${{ matrix.destination }}
