on: 
  push:
    branches:
      - 'master'
  pull_request:
    branches: 
      - '*'

name: CI
jobs:
  test:
    name: Unit Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=macOS,arch=x86_64']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild -project PomodoroCookie.xcodeproj -enableCodeCoverage YES -scheme PomodoroCookie -destination "${destination}" ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO build test
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
